phb_base_index:
    resource: "@PHBBaseIndexBundle/Controller"
    type:     annotation
    prefix:   /

phb_base_contes:
    resource: "@PHBBaseContesBundle/Controller"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

dt_catalogue:
    resource: "@DTCatalogueBundle/Controller/"
    type:     annotation
    prefix:   /
