services:
#    dt_catalogue.example:
#        class: DT\CatalogueBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    dt_catalogue.listeLesCodesContenusDansLaLigne:
        class : DT\CatalogueBundle\Services\ExtracteurDeCodes
